baseURL = "https://www.flyinggrizzly.net/books-what-i-read/"
publishDir = "public/"
canonifyUrls = true
languageCode = "en-us"
title = "Books what I've read"

theme = "learn"

metaDataFormat = "yaml"

[params]
  description = "Books I've read"
  author = "Sean DMR"
  showVisitedLinks = true
  disableBreadcrumb = true
  disableNextPrev = true
  themeVariant = "books" # choose theme variant "green", "gold" , "gray", "blue" (default)
  disableSearch = false
  disableShortcutsTitle = true
  ordersectionsby = "date" # ordersectionsby = "title"
  disableAssetsBusting = false
  disableInlineCopyToClipBoard = false

[outputs]
home = [ "HTML", "RSS", "JSON"]
